### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by apollonxy** [akkeyron/genshin-rpg#1]
.

**Comment by loqmandev** [comment]
Some of them redundant, and some of them are not used in the project anymore.

**Comment by loqmandev** [comment]
> can i use ur bot?

I havent deploy the bot. Which source code did you used? I can send it to you here

**Comment by apollonxy** [comment]
i used your repos source code and i changed database  but if u send codes im will be so happy

**Comment by apollonxy** [comment]
> > can i use ur bot?
> 
> 
> 
> I havent deploy the bot. Which source code did you used? I can send it to you here

<3

**Comment by loqmandev** [comment]
hey bro, I push the codes that I deleted in /old_codes/ folder

**Comment by apollonxy** [comment]
> hey bro, I push the codes that I deleted in /old_codes/ folder

thx bro can i gave ur dc nick
